from __future__ import annotations

SEEDS: dict = {
    "instagram": {
        "hashtag": ["mochilero"],
    },
    "tiktok": {
        "hashtag": [
            "mochilero", "mochileros", "mochielando", "mochilera",
            "viajero", "mochila", "viajando", "viajera", "traveler",
            "viajes", "voluntariado", "voluntario", "voluntaria",
            "lowcost", "budget", "house sitting", "contentcreator", "porelmundo",
        ],
        "keyword_search": [
            "ahora en Río de Janeiro", "actualmente en Pipa",
            "viajando por el nordeste de Brasil", "en ruta por Florianópolis",
            "explorando Jericoacoara", "recorriendo Búzios",
            "hoy en Río de Janeiro", "día 5 del viaje en Florianópolis",
            "seguimos viajando por Brasil", "vivimos viajando por el litoral brasileño",
            "siguiente parada: Pipa", "estamos en Jericoacoara",
            "de paso por Búzios", "historia de hoy desde Pipa",
            "subiendo contenido desde Río de Janeiro",
            "ahora en Barcelona", "actualmente en las Islas Canarias",
            "viajando por el norte de España", "en ruta por San Sebastián",
            "explorando Valencia", "recorriendo Sevilla",
            "ahora en Roma", "actualmente en Venecia",
            "viajando por el norte de Italia", "en ruta por Florencia",
            "explorando Milán", "recorriendo Nápoles",
            "hoy en Roma", "día 4 del viaje en Cinque Terre",
            "seguimos viajando por Italia", "vivimos viajando por la Toscana",
            "siguiente parada: Florencia", "estamos en Venecia",
            "de paso por Milán", "historia de hoy desde Nápoles",
            "subiendo contenido desde Roma",
            "hoy en Madrid", "día 7 del viaje en Barcelona",
            "seguimos viajando por España", "vivimos viajando por la costa española",
            "siguiente parada: San Sebastián", "estamos en las Islas Canarias",
            "de paso por Valencia", "historia de hoy desde Sevilla",
            "subiendo contenido desde Madrid",
            "ahora en Berlín", "actualmente en Múnich",
            "viajando por el sur de Alemania", "en ruta por Hamburgo",
            "explorando Colonia", "recorriendo Fráncfort",
            "hoy en Berlín", "día 3 del viaje en Heidelberg",
            "seguimos viajando por Alemania", "vivimos viajando por Baviera",
            "siguiente parada: Hamburgo", "estamos en Múnich",
            "de paso por Colonia", "historia de hoy desde Fráncfort",
            "subiendo contenido desde Berlín",
            "ahora en Zúrich", "actualmente en Ginebra",
            "viajando por los Alpes suizos", "en ruta por Lucerna",
            "explorando Interlaken", "recorriendo Berna",
            "hoy en Ginebra", "día 5 del viaje en Zúrich",
            "seguimos viajando por Suiza", "vivimos viajando por los lagos suizos",
            "siguiente parada: Lucerna", "estamos en Interlaken",
            "de paso por Berna", "historia de hoy desde Zúrich",
            "subiendo contenido desde Ginebra",
            "ahora en París", "actualmente en Niza",
            "viajando por la Costa Azul", "en ruta por Lyon",
            "explorando Marsella", "recorriendo Estrasburgo",
            "hoy en París", "día 6 del viaje en Niza",
            "seguimos viajando por Francia", "vivimos viajando por el sur de Francia",
            "siguiente parada: Lyon", "estamos en Marsella",
            "de paso por Estrasburgo", "historia de hoy desde Niza",
            "subiendo contenido desde París",
        ],
    },
}
